name: Terraform Init and Fmt

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform Init and Fmt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6  # ya aapke required version ke hisaab se

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
